id: tihagura/coord
name: coord
overview: 中心座標移動スクリプト
description: オブジェクトの中心点を動かすスクリプトです。
developer: はち
pageURL: https://www.nicovideo.jp/watch/sm32870150
downloadURLs:
  - https://1drv.ms/u/s!ApBRDdKWwHOHa-y7KbDuPFVpQMY
latestVersion: v1.2
nicommons: sm32870150
files:
  - filename: script/coord/coord.anm
    archivePath: coord/
