id: suzune/bakusoku
name: bakusoku.auf
overview: AviUtlを爆速化するプラグイン
description: ウィンドウの描画処理を変更して、動作を軽くします。
developer: 鈴音
pageURL: https://www.nicovideo.jp/watch/sm39679253
downloadURLs:
  - https://github.com/suzune25254649/bakusoku_aviutl_plugin/releases/latest
latestVersion: v1.06
nicommons: sm39679253
files:
  - filename: plugins/bakusoku.auf
    archivePath: bakusoku_aviutl_plugin-1.06/
releases:
  - version: v1.06
    integrity:
      file:
        - target: plugins/bakusoku.auf
          hash: >-
            sha384-R88BgBkWqGyNV7k17Rs1pdSExz5BvYpAjezWiQLL3xalz4LabnEKcZhBx2pSt7EB
