id: rikky/relativePath1
name: 相対パス保存(rikky_module 1)
overview: 保存したとき画像のパスなどを相対パスで保存するプラグイン
description: 保存したとき画像のパスなどを相対パスで保存するプラグイン。
developer: rikky
dependencies:
  - rikky/rikkyModuleMemory
pageURL: https://www.nicovideo.jp/watch/sm31884370
downloadURLs:
  - https://hazumurhythm.com/a/3Av/
latestVersion: v0.9b
nicommons: sm31884370
files:
  - filename: plugins/relative_path.auf
    archivePath: relative0.9e/rikky_module ver1用
releases:
  - version: v0.9b
    integrity:
      file:
        - target: plugins/relative_path.auf
          hash: >-
            sha384-CqpL1vL5ul1SsUvNXLASHSGe431dfVZlvxBJH+wjCJNVsmYfo5iC2BwfgFDCTDYJ
