id: satsuki/soundwave
name: 時系列音声波形
overview: 音量の変化を時間軸に沿って表示する
description: 音声データを記録し、そのデータに応じた波形を表示します。
developer: さつき/ティム
pageURL: https://www.nicovideo.jp/watch/sm16297007
downloadURLs:
  - https://www.axfc.net/u/2153704
latestVersion: 2012/08/07
nicommons: sm16297007
files:
  - filename: script/satsuki/@onsei.anm
    archivePath: 時系列音声波形
releases:
  - version: 2012/08/07
    integrity:
      archive: sha384-xbZmgeAArDSSIEDj6rySMORq9MYDWFx5ZmQ/Iu9FnsoaNUO+ZtH1NY0if5fdK5Q6
      file:
        - target: script/satsuki/@onsei.anm
          hash: >-
            sha384-NNfwINDAZNCAKDzXIfJAoroPNkt8X4hCS1iIXWegLQcElUYUwSFJOe80wZ16n8WK
