id: aoytsk/jumpbarx
name: ジャンプバー＋
overview: 様々なジャンプ機能を提供するAviutlプラグイン
description: >-
  ジャンプバー＋
  は様々なジャンプ機能を提供するAviutlプラグインです。フレーム・秒単位の相対位置ジャンプや、編集点・プロファイル変更位置へのジャンプ、マークやコピーしながらのジャンプなどが可能です。
developer: aoytsk
pageURL: https://aoytsk.blog.jp/Aviutl/719123.html
downloadURLs:
  - https://aoytsk.blog.jp/Aviutl/719123.html
latestVersion: Ver 0.4.1
files:
  - filename: plugins/jumpbarx.auf
