id: shummg/shuGame
name: shu_game
overview: 「オセロ」や「マインスイーパ」の動作に必要
description: 「オセロ」や「マインスイーパ」などに要求されるスクリプトです。
developer: しゅう
dependencies:
  - rikky/rikkyModuleMemory|rikky/rikkyModule2
pageURL: https://shummg.work/downloads/#%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA
downloadURLs:
  - https://github.com/shumm7/AviUtl-shu_game.lua/releases/latest
latestVersion: '1.1'
isHidden: true
files:
  - filename: script/shummg/shu_game.lua
releases:
  - version: '1.1'
    integrity:
      archive: sha384-soXtIGntr1QO/jvsrUcIvPvv6YjrfI45qS1tRF7nlv0B5t8HcyMPS1/jK8xBa2OD
      file:
        - target: script/shummg/shu_game.lua
          hash: >-
            sha384-qFXsL73G/vC9lo4sUqqtkqqIG/TP8ZGcKrbCylto/YJeWw1BibUPkS4tnNQZ/6vC
