id: hebiiro/UltimatePlugin
developer: hebiiro
downloadURLs:
  - https://github.com/hebiiro/anti.aviutl.ultimate.plugin/releases/latest
name: アルティメットプラグイン
latestVersion: r97
overview: AviUtlを使いやすくする複合プラグイン
description: 蛇色(へびいろ)制作プラグインを１つに統合したプラグイン
pageURL: https://github.com/hebiiro/anti.aviutl.ultimate.plugin/wiki/
dependencies:
  - aviutl1.10
  - exedit0.92
  - hebiiro/python32
conflicts:
  - ePi/patch
  - nazono/patch<=r43_42
files:
  - filename: plugins/ultimate
    archivePath: plugins
    isDirectory: true
    isUninstallOnly: true
  - filename: plugins/ultimate.auf
    archivePath: plugins
  - filename: plugins/ultimate.aul
    archivePath: plugins
releases:
  - version: r38
    integrity:
      archive: sha384-lz85EanJbsWmpwzg3WnZdSi3RqURPr1c3VUIXrRmQ4tk58LFoks3pjzky5yAVTTG
      file:
        - hash: >-
            sha384-Q5GoWcXGAmFcQUe2nPKrODQ9qgHX7/GjcCrAs+ALo54Dg6Ns2YOXezkgqtV3B+b/
          target: patch.aulの設定.html_local
        - hash: >-
            sha384-+wk+lYuye44KLsJ8zyzJwtfvGQL1hOMmL0NwwH4ME31Z4yZacGdMaca37Ymbp0EP
          target: アルティメットプラグインの設定.html_local
        - hash: >-
            sha384-x/5uEnq23wbaVB0ozHnu6m7kbWyMxcgmHnhhBsoWlpks6EhlgkN/eD05j61NSZ3k
          target: ultimate.auf
        - hash: >-
            sha384-HO3vnD3WQZQSQQv6yHDUVXjc6xZWIzjL4LOES0VIq1LHGGiCMhUMXrIZZPhLQJin
          target: ultimate.aul
