id: MrOjii/LSMASHWorks
name: L-SMASH Works
overview: 様々な形式の動画・音楽ファイルを読み込む
description: >-
  様々な形式の動画・音楽ファイルを読み込み可能にします。VFR-maniac氏が L-SMASH Works 開発の一環として実装を進めている OSS
  のMr-Ojii氏版です。Mr-Ojii氏により毎日最新のffmpegを用いてビルドされています。
developer: Mr-Ojii
originalDeveloper: VFR-maniac
pageURL: https://github.com/Mr-Ojii/L-SMASH-Works
downloadURLs:
  - https://github.com/Mr-Ojii/L-SMASH-Works-Auto-Builds/releases/latest
directURL: >-
  https://github.com/Mr-Ojii/L-SMASH-Works-Auto-Builds/releases/download/build-2025-10-12-01-16-57/L-SMASH-Works_r1245_Mr-Ojii_Mr-Ojii.zip
latestVersion: 最新
isContinuous: true
files:
  - filename: plugins/lwcolor.auc
  - filename: plugins/lwdumper.auf
  - filename: plugins/lwinput.aui
  - filename: plugins/lwinput64.aui
  - filename: plugins/lwmuxer.auf
  - filename: lwcolor.auc
    isObsolete: true
  - filename: lwdumper.auf
    isObsolete: true
  - filename: lwinput.aui
    isObsolete: true
  - filename: lwinput64.aui
    isObsolete: true
  - filename: lwmuxer.auf
    isObsolete: true
releases:
  - version: r1145
    integrity:
      archive: sha384-OLxFWAyQiTdzLLLbdfqJSDdYtJooJn4cm0EzvcPqQlpGEzVEp86dyGUYwckOIK0w
      file:
        - hash: >-
            sha384-/l4b2GZh3Z94K2BlIuNI5UxsG1GFi0ih/o6NegMEpKsxEAmniR1RCGNMP3Xa9e71
          target: lwcolor.auc
        - hash: >-
            sha384-o1+z9M4egfYxVx20XSwYVzS/2uTF8k9G5qRtWDuri12GruhHNkibvX5mVMhzUcdL
          target: lwdumper.auf
        - hash: >-
            sha384-aWq7DoHxHLjVa4if+B2CUaP4Fbgvh2gssINiKsqictZtW3dyp+BetqW42BnQBkRV
          target: lwinput.aui
        - hash: >-
            sha384-lUHKN12GrbNeYsAcVNsJA7tZoNkm0peqadLjmXu7UHUG/+CgAXxRSw+6wL7oeGIb
          target: lwinput64.aui
        - hash: >-
            sha384-n1vlT4QlNTtEvArWYxKFfE3a6SMR8zHrlhNzcHAqZrQnSsugCkDAaz2xAL0jr7Ac
          target: lwmuxer.auf
