id: jigno/dueltap
name: 架空デュエル_タップ・アンタップ
overview: カードをタップ/アンタップ（90度回転）するアニメーション効果
description: 画像にタップ・アンタップ（画像を90度回転して寝かせたり立てたりする）のアニメーションを付けるスクリプトです。カードゲームを扱う動画に適しています。
developer: jigno
pageURL: http://onomirukust.blog.fc2.com/blog-entry-172.html
downloadURLs:
  - https://www.axfc.net/u/3822110.zip
latestVersion: 2017/07/06
files:
  - filename: script/jigno/001_Tap-Untap_02.anm
releases:
  - version: 2017/07/06
    integrity:
      archive: sha384-TxZeO9M7Z6FvTHyfIgNFsGM2FM0QBlmbqKonXQqH/NXjZHccFHYv6yA3e4Upp8cl
      file:
        - target: script/jigno/001_Tap-Untap_02.anm
          hash: >-
            sha384-p6JKSCsTho1BWZw1eUU6tGZE16skH/vbI72Ge+7IbTLJqtVPYqyzAdFclYHS4THA
