id: ePi/LuaJIT
name: LuaJIT
overview: スクリプトエンジン「Lua」の高速版です
description: >-
  AviUtl(拡張編集)のスクリプトが使うスクリプトエンジン「Lua」の高速版です。【アンインストール方法】このパッケージは拡張編集を上書きします。そのため、このパッケージをアンインストールするときは拡張編集の再インストールも併せて行う必要があります。
developer: ePi
pageURL: https://scrapbox.io/ePi5131/LuaJIT
downloadURLs:
  - https://scrapbox.io/ePi5131/LuaJIT
latestVersion: 2.1.0-beta3
files:
  - filename: lua51.dll
    isInstallOnly: true
releases:
  - version: 2.1.0-beta3
    integrity:
      archive: sha384-hfvjNiRmpKd+MbPaJANABNkbqtE2Z/w+V3k3wWXUX8I2w9vQn9DtLYout4up1RAQ
      file:
        - target: lua51.dll
          hash: >-
            sha384-Tyx0ziJxtuafsPaBhg6OLWnKyJKE/cpfY5E+ixylKFsXeduy5j4b4AUhp3GtLuP4
