id: ePi/export2clipboard
name: export2clipboard
overview: クリップボードに出力画像を転送する
description: |-
  ファイルに出力するのと等価なイメージをクリップボードに転送する。
  ショートカットキーを設定することが可能。
developer: ePi
pageURL: https://scrapbox.io/ePi5131/export2clipboard
downloadURLs:
  - https://scrapbox.io/ePi5131/export2clipboard
latestVersion: 2020/09/04
files:
  - filename: plugins/export2clipboard.auf
releases:
  - version: 2020/09/04
    integrity:
      archive: sha384-e+P1yzycQzZ3BA0j4tD+EOTDZNTsZ+7Ey+Bh2GwgWWh5C8clKUwGgtdjzbGBW8ha
      file:
        - target: plugins/export2clipboard.auf
          hash: >-
            sha384-e+P1yzycQzZ3BA0j4tD+EOTDZNTsZ+7Ey+Bh2GwgWWh5C8clKUwGgtdjzbGBW8ha
