id: hebiiro/DarkenWindow
name: 黒窓
overview: AviUtl の見た目をダークモードにします
description: >-
  AviUtl
  の見た目をダークモードにします。【旧版からご使用の方へ】aviutl_dark.exeは廃止されaviutl.exeからの起動に統一されました。
developer: hebiiro
dependencies:
  - exedit0.92
  - ePi/patch|nazono/patch
pageURL: https://github.com/hebiiro/AviUtl-Plugin-DarkenWindow
downloadURLs:
  - https://github.com/hebiiro/AviUtl-Plugin-DarkenWindow/releases/latest
latestVersion: 8.1.0
files:
  - filename: aviutl_dark.exe
    isObsolete: true
  - filename: aviutl_dark.exe.manifest
    isObsolete: true
  - filename: plugins/cc6.manifest
  - filename: plugins/DarkenWindow.aul
  - filename: plugins/DarkenWindow
    isDirectory: true
releases:
  - version: 8.1.0
    integrity:
      archive: sha384-ekm6UxlGfrXNsjLM+QqRuik6Vq1FOCuRLCVBCoLBc0a7285dTGhjwLI8lK2UQQCz
      file:
        - target: plugins/cc6.manifest
          hash: >-
            sha384-11n1+bSomxXm3gxNJp4N1im9r7HsJ8wWR1Wk6wuxOpVQNE71XKBuvZEQDHSHeOxi
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-kqWrXS2dbUBnEUnc0D/Icfj3swY9itzQqplRs/Un1I/dB/ay1sgnfTzuU0k9g70N
  - version: 8.0.0
    integrity:
      archive: sha384-Z56F2O3JUhruYsIAr+JJF2JLOhWHksnb8MFdJo1Ci0tftlhrBSKvPxvHiIHsHyJ2
      file:
        - target: plugins/cc6.manifest
          hash: >-
            sha384-11n1+bSomxXm3gxNJp4N1im9r7HsJ8wWR1Wk6wuxOpVQNE71XKBuvZEQDHSHeOxi
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-KYRrtaEYwpdgBFVLN9BlO7p3iTCxC/GMn9upnxNVeCJxuCPEDtAiLgfSEvdRw5Fx
  - version: 7.3.0
    integrity:
      archive: sha384-QDutXJWCWBFUoCAclzvcCdoU2ZKm7kV7SQCjY8/DpzWGexnqRnXe5USdt+U3hNhj
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-5bMab2aZnMXsouLJHtvPopFG/oZi9zbAz0KPmAd0R4tdB1ZlSyKH9QM8D55bHKDu
  - version: 7.2.0
    integrity:
      archive: sha384-IQPBlC4/ah0DO7PcVNESD7xZPcXBuAf534fnnZ8PdVfC1uG0tsLTxQ8nK3z9ZAiL
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-BKscr+qLYYwmo1midhOUvzpRtOY91MLnMihFpNj0qi4Wop6e0TL/3uHTWX9wWR3q
  - version: 7.1.1
    integrity:
      archive: sha384-rHkuC6qBRGl2+Ett6eEX8yuchPNerjf6rg9i10DteG2jxWHeS1+UZloERdFKu0iX
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-uwOEoXoS2bedpkmimJm4vlE0WIt5JiIVLdRscj0CaiOx7NsDr9+qeso6DmtP9XbU
  - version: 7.1.0
    integrity:
      archive: sha384-eT9sx8m/dgNK8Fcf+d6CuJgJTKcju2/7+qkW7/NQ3VPrq5QSSt6yfjcyyCFdP3VY
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-2gnB7a0xStSi/d1QnetWCtTAIDZ5m5C/YyMlFy9saSufpZVnymDz2SJfdHjGEsLn
  - version: 7.0.0
    integrity:
      archive: sha384-9nix158gziRjvJ7Z5Kbnku4DLzWuvkCZIjQBpsmpJhxhXTxPoFyyiDQ1+hx2fSVy
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-OTMFD7GH1+ZtUcmiMST8XonjgsbHp552/D+AZqF57Ox16H8hXYMX2YZlsH/s+GT4
  - version: 6.9.0
    integrity:
      archive: sha384-N8U5AqPsH6t7Okv8WWflMei2LOzIjQLE+ifnFL0IhkyfnP7cbFYKf3oR7qtwSHsP
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-+31P0OD9YgnbkdjQGuGKVCFiF9KOUpDaf6Fi87/CrRo+fFKryClEbveQvyyhhBpi
  - version: 6.8.0
    integrity:
      archive: sha384-SZkdK5Y5v/5i7SL0w+jdYVery3SIl/Ij9OJt7GpVl/S23dmjapYpVfcUgmT5tAAw
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-eq3Y9x2XS0gliTHaZ/gMfe2bQUTP/g2sHlscyiOYDTBS1wb/jaNdo/etJd7YRkzM
  - version: 6.7.0
    integrity:
      archive: sha384-vYeYXqIObtQcZ7rLa7g/VCvFwWc8VKy8jFm+8uUSZdd2jXy1mOvTTu9S/I7jAsCR
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-DBv3Mqmc/pox/2LdaLPRv+B3lUmuBAhothfASAjqZ0ISHMBAA65sDg2o+EpDG8ui
  - version: 6.6.0
    integrity:
      archive: sha384-d3FwYjrg6ZHvR20ksiePXxY8oBiZSJ8tI2n2wXnYceRyv87YGB6oTQD2BXbCDZI2
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-XoYhWM6cvSxqpo9PBlnCdfPFUXbyV7tksNM8ZVvY1sDdTAAr3W6Vjd5hDqH8yc50
  - version: 6.5.7
    integrity:
      archive: sha384-WarEU1aJxsme1Iyc8Xk8x1TqZbov+R46Y3KDbjfXgeCp3X1ttvw17hjXqD2HPJ+j
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-ClzYW+X/De1wBb5sjhZ7vnLn+ZQ2TzMUnAToZBUc2is0unVjYy3XnpFkMyzLsumJ
  - version: 6.5.6
    integrity:
      archive: sha384-ScnznPmH98m2y1dB1RQkYd9BbYw9MK4Uixv4hfhGDpuoSvp7imokj2fl7Bze7/nR
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-DeWKBm3mWqGsLDj9Ej+MqefITuV+HFdx8xK8xhtemp7LxpHs+AOr0Vi8f8g7qTEt
  - version: 6.5.5
    integrity:
      archive: sha384-f+dQ5T9hr9nU1JiLQBitUjM/xiOK0Wo1j3mPlmU23Sr+/kICzjAJ2YogOa5aDzAP
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-/4vnbVjgnKg74ZZ70XbWFVFUgAZUQh/CvwPTTJNHerwhomICvjikwIKnRovC0iGW
  - version: 6.5.4
    integrity:
      archive: sha384-Jnl+OeQNQhJthLFDAyuzgVqHGat6ZUt66se2VBeG6NmnZtwYc5oaYPFT67rP1x2v
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-/zwWMO3BoSf7feGzQgLvVPcBwbi2nJpOhNkX/Itvr4ZyJhdZMTwuarUMzsMB+DX4
  - version: 6.5.3
    integrity:
      archive: sha384-4EV1Gp/tpPgWvO0mniY/Zxc0QrDcusYfWCJ0SFklpIt+c1kv8oAup9jT4Z73LS9C
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-aErLhcBsdHK2epUoprs6wTgPD8EzP2IZteLFkFHJVSYpSgEXMTN2/JFf0g+6QFwc
  - version: 6.5.2
    integrity:
      archive: sha384-T+bMrR7kmaZ8qtjHWZEBLq5mZPPLC+fvk97pTDtht3XinRREVtREDlPlOUuxJaoQ
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-YUkAf1w5BRBIAcs+bkROQkIXgWCXHHU/yoUEqxrLwLZDHB/jbYHLH0Fu1OruJJPN
  - version: 6.5.1
    integrity:
      archive: sha384-wHkuu/8SDLDdir77eR8CgkOZuBJOZktBQ2GBaQO4glfEt1rbCDmgycl/J6uf1KQl
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-KCyOLnJviw9HGC4cXs3lf3fgFPwDDXxgofp07Lb43uLGwBpt+hHjD/f1Hznr5UZO
  - version: 6.5.0
    integrity:
      archive: sha384-vDETSXF/Y6r9FItBaTqBxJ882hYKh+/wX1Opz0GVRluhD8IZW7h+ntau1ZeI7oLc
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-KCyOLnJviw9HGC4cXs3lf3fgFPwDDXxgofp07Lb43uLGwBpt+hHjD/f1Hznr5UZO
  - version: 6.4.0
    integrity:
      archive: sha384-zfvBZCI4GRfCpONXSiAaRbfjRl23rBt6rJq2bx2/QtFNUulG1yZ7/w9U6zeilHHE
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-1UWv3Ycc05NyySa3IX0uFi7J2QG3Bh8o/tEvwjOr7fmtm+p8qCvlGOTRbd4CHAzs
  - version: 6.3.0
    integrity:
      archive: sha384-g0w2TLLfiXegN8Efpks4hkdNs7ESSznCRZ4XK3tLKfe3uWqvfguyi2PzOPyxKEiv
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-CDLl7NMHQoUde4YQh4jOQ+BSE5AAX9y0GFxHbPwcRLsc4a0ABYXr6/7RTVbKCFih
  - version: 6.2.2
    integrity:
      archive: sha384-PWdhdi7YHWIDtrecEGO893vollJozB8w44BH0uUA84ZNbUGo6GaTKVTPf9V3A6Pz
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-DDQcKUbxIP46YAiS1SKH0lvahq/+84O8dvPovofYQ85BHNqS7IN7uUN8tuLYoemD
  - version: 6.2.1
    integrity:
      archive: sha384-vXt9a02oZWghVrifv/ozzk7T3NxfepAi1bTCuNdKMD8AN7T5K1CkXY9nB4PaZjH4
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-YwBWyHTYmI+ngnr+Yb/Pgh53TGDBRYl+BdWliikDv0+1wX+9rVO1tGHGPGYpQid6
  - version: 6.2.0
    integrity:
      archive: sha384-o3LnCBXbsCG/eIc5TJT9ioMxhSl+nZ+FLWWlp+O+aBZCUm90eFK/Fe7v79I2QfqQ
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-S8rTJyc20ETFQ2JNFqTMefXtG6jEodgtbFdiqaeMgNV+WfdPYvoFgvM4QL8A4ZG4
  - version: 6.1.3
    integrity:
      archive: sha384-dQKI2eiKGjip5lg1nEUXW6i5+5wHZu9QGHSSWty7+ExmFqcevZKeUiajd4aiKehp
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-F5Nc3trbnfIcDxt8MjWjBvD563cC3l3UgAPPHaXJH0+6WKsndcSPGUiIOUa6jesY
  - version: 6.1.2
    integrity:
      archive: sha384-o0rrH/RLxt+VI2FLt+nc9ziX9umYGa+IGIQaU2h1K0O55qscx4SWbb6LypjID6Z8
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-guhUUBRWZ/gUzos1WzSh+mnLjw28NUhXWlGA9zxBsi2gC6tXxB4VVPkqHzEv7t9T
  - version: 6.1.1
    integrity:
      archive: sha384-RHfrEW7SPOxDqCVIlMdTDFu1PkM9+OnK61YyttzN6KGYoiTCRvtacMmCPumnuFz1
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-azg2v4PoFmzI3GmlAOCXOz/N+OCXNpwYW/+0be4E/JlJVqnbigr0+T9fvrh1Cr65
  - version: 6.1.0
    integrity:
      archive: sha384-dBDTaxZOp+uQZxlkNFAkwnPVG9xJgMBnMIuZClEhKaHKV+q2Adqcbw/x2J0TM2Um
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-0MAzoX+A1Q8yZg5vrx80ZhyDGmBPGGPVz20ts9pKl1yds6NSlZMzmgcMeY9xzMnn
  - version: 6.0.0
    integrity:
      archive: sha384-n5b2PlXxTKP6WG/wSGkDX1CtSHeSY653bcQH/4FGN/FhM1YwiF0M84PQGYxq6ucS
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-Il6qqO2CPZW0qMGROamQvG+hpfHxTGrzLPPNuOz+TPfDEhTyFclr1mUwkCC9aFYt
  - version: 5.5.0
    integrity:
      archive: sha384-VuVlTlwLDbzUJTu/2A/3L2qZBPHSRUG6wyD/sy4ZCNWW08nba/8eAtmGOuSzDlHh
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-UH9VOa90fqbxl3E++vQYxk3HmcvdnHbgZHDmao8IedhgFO7JjXgIp3Kp1+2LB1Z4
  - version: 5.4.2
    integrity:
      archive: sha384-k1cFmU3cN3W5gNS314SxGPa6cJHubna9LnpNzJKeSMS7qCea4oh5ZK6pfsSQo7lr
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-UH9VOa90fqbxl3E++vQYxk3HmcvdnHbgZHDmao8IedhgFO7JjXgIp3Kp1+2LB1Z4
  - version: 5.4.1
    integrity:
      archive: sha384-74QqSIOpGc5BTfaOkoQQu628xxfREJ3GL9SnCtV31nlOEaR0xYn7Gc88GiDDL8qt
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-JxaPtOdLt5ayhpk8n6sd+eNXYJRln0GnDKz0v39wB7zKrx5q6/EMuA3vDnXPXN9J
  - version: 5.4.0
    integrity:
      archive: sha384-8GfZ3aeC5ZJxpfvEbxpZsFQHDlOcrPdjIeHaHz4yydk2tl9Prr2qllBdYa5lcUXd
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-tnxmWxfB/P6UaTgrAiLEhPmUkSCthBqtbKEFPIglWlYClZxub9Yz7zVUl6yDV5dk
  - version: 5.3.0
    integrity:
      archive: sha384-IgzKAUM3ZhzaDdKpInTlEtutRyV+uNakt1Ij4kGtnATv/bfH7pQAuAToSAlKdQ53
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-tnxmWxfB/P6UaTgrAiLEhPmUkSCthBqtbKEFPIglWlYClZxub9Yz7zVUl6yDV5dk
  - version: 5.2.0
    integrity:
      archive: sha384-WQG4KK7YFRsYnO2WdzDNIFI5inyMdc36zjnSnpzmDqlpFwHnPI+6O+Slwhg+ffRX
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-sCde0B5WLXxDLMTYaANS2Me0IET05SZw/xA0KhKiiL/ITELLiUCa6MYRJbHaSz2W
  - version: 5.1.0
    integrity:
      archive: sha384-mjB9uB/DpPz8uNkF4RQhi/s4cR1DUfOOXThLMW6+4xwduPehVG0EVFUEaUzNDwbA
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-QIgWJhzKje1DWU8xv6tCA0KDgJZ+eGRtSkWcHE+FIOna5ZM1y5ssQmNrnxUJlLsd
  - version: 5.0.0
    integrity:
      archive: sha384-FGsijtOZcM8LsYp69vHYmK+o8uBaJX2bKxlPWcZyAqo4+jTbWWiluKtLI7jkDW9Q
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-c9GKzbdIMkR+Vr9Cgo3Br1p0a1xD09ttXXx1RI9u0/sCMj77z9FDPtr+bUOe5EMw
  - version: 4.2.0
    integrity:
      archive: sha384-NV6mHnmqehr6/omPjXMR5R1RnaUmased5tERz+4ZXZE6sxskq3FItG7kyZcPhEZE
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-iqn1PzuS2jmfx2KaUds34VPdzYFJp0YP/t33aUp3Z2rThbIy7oHCn794xp76Eq3n
  - version: 4.1.1
    integrity:
      archive: sha384-Xv3anZ1kabK5hHqnbdDDsx9SmrHK9eSzMiwDTbUcCSQ8MxEbe9i2zNKrkqnRMTQQ
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-YiNjXepf161foUVKd68wYN7uEafvnWVxrs3LNTTARQFh8qtdWloMuTN99N4Ee0Uu
  - version: 4.1.0
    integrity:
      archive: sha384-Ue66waoywrIg/GRyKh/aBfJZx8i8NqqSVVF7eHSzHqTQzal9S853va3UDlyGnltx
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-QaYqmv5DzTcsb/SDVmZpZQsMC3gFu2rwYFec7AMEqMXY8vselOWwdajOXw7jBPFE
  - version: 4.0.0
    integrity:
      archive: sha384-IQXTXAmaOU6xVIhZY+O2nyw9Z2l2JVcMvyA9daGpRuyQpK39u4+yVqLFGTDlFnU7
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-AEG2HN/lGxo8mm02uNDLdsqjiQfPqQv3It80OYml+SxlC5yEU34ZfNouuy6W5RAx
  - version: 3.2.1
    integrity:
      archive: sha384-wE2MSOXq9qoMKl3pwqqouNL5/OSF+8BMPTSA4CAk122dBwx/+rCR8bNt9v/x4ucz
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-Jw2vQi98xMujxd7LzsdrS44cFvg6eBVlQeyQe0W/cSXzwDR+sql2kzy9Vc33GTP7
  - version: 3.2.0
    integrity:
      archive: sha384-MjIcNDcllaLSMzb99BJAwowQq8T00+tTFwz0xABbRAoX+c7cCtck7+UqixZLti6+
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-EFpI/syvSdkvvJzb1uhiiGofgWa1eGcnDdytptT8P3bNp0Lkx0b37FteVEPyyLJO
  - version: 3.1.0
    integrity:
      archive: sha384-FSEMtZBGwJ6escRMjaHKIPm69ns3wNjYTRFmMZWnSlMQ5hLfnf9mdX0BnYdxBL/T
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-Dd08YJOaEpbZJR5Nuk0ViwxhRS7OimMEFnW7rOcJLzAJMml6Km49oqazMXikXUfz
  - version: 3.0.0
    integrity:
      archive: sha384-EoUNTMJHQa8Tzm+a7Uf6HIMi+U6aroipjALbV/7we6Aiwe1Rzi8MSZDN7tRaomhR
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-sVdIh5G2gVW1KTkuttr8yhUOI8fEGSpn2hJ3C+YhyQU6OsLOh7eKcltTab5fsPaY
  - version: 2.0.4
    integrity:
      archive: sha384-Dct043yQCL6hCXRi9rNEzyqkEvYGu2hQQf4pE8t8r0iwJQtTdhYrP7oyKSe5O0mR
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-jYVhDSUMsgqvhKDCYD3tEYMlaC3VjphIjTYbRGpqxcg3Ei7oa+yczTlFk15c7EtZ
  - version: 1.1.2
    integrity:
      archive: sha384-jYeggq6yZYhQ2zAJkhbYNR81dzTH2DmePBn1pgamb//UtUcMJpJuPc1u1jBk3EZ2
      file:
        - target: plugins/DarkenWindow.aul
          hash: >-
            sha384-ZGqBxDYXqeo9+VrSGeq150A6ELmd9itFXYydu3oe7mz9C44s/rdm5ZwNdecr3RWr
