id: aoytsk/seekbarx
name: シークバー＋
overview: シークバーにサムネイルを表示する
description: Youtubeのようなサムネイルをシークバーに追加するAviutlプラグインです。
developer: aoytsk
pageURL: https://aoytsk.blog.jp/aviutl/613302.html
downloadURLs:
  - https://aoytsk.blog.jp/aviutl/613302.html
latestVersion: Ver 0.3.1
files:
  - filename: plugins/seekbarx.auf
