id: sets/tim
name: ティム氏のスクリプト
overview: ティム氏のスクリプトセット
description: https://tim3.web.fc2.com/sidx.htm にて紹介されているスクリプトのセットです。
developer: ティム
dependencies:
  - tim/rgline
  - tim/hevbunr
  - tim/sket
  - tim/lineex
  - tim/crkgls
  - tim/ruledl
  - tim/lowres
  - tim/pour
  - tim/linefil
  - tim/barcode
  - tim/coladj
  - tim/famili
  - tim/framing
  - tim/blolus
  - tim/pyopyo
  - tim/halfres
  - tim/conline
  - tim/mltline
  - tim/reelrot
  - tim/windshk
  - tim/stroke
  - tim/twitch
  - tim/linhal
  - tim/roughe
  - tim/traspe
  - tim/mtile
  - tim/bezspe
  - tim/fitset
  - tim/trapnt
  - tim/splmrp
  - tim/colext
  - tim/combst
  - tim/wire3d
  - tim/traeasy
  - tim/auradcg
  - tim/scechg
  - tim/starbst
  - tim/bompuz
  - tim/skydome
  - tim/rbwgra
  - tim/chroma
  - tim/frame
  - tim/26poly
  - tim/radpar
  - tim/curtra
  - tim/nslime
  - tim/briwipe
  - tim/grdwipe
  - tim/twister
  - tim/coledge
  - tim/pickup
  - tim/ink
  - tim/split
  - tim/beehive
  - tim/polyhed
  - tim/cstfla
  - tim/filmscr
  - tim/shake
  - tim/diasha
  - tim/polcon
  - tim/access
  - tim/lightng
  - tim/glasssd
  - tim/mmdcam
  - tim/autotgt
  - tim/lburst
  - tim/vanishP
  - tim/vanishP2
  - tim/polycut
  - tim/esyrpt
  - tim/polygon
  - tim/bubble
  - tim/outlpur
  - tim/tmppre
  - tim/polcgra
  - tim/brokenb
  - tim/glpast
  - tim/embtile
  - tim/broken
  - tim/simwrp2
  - tim/simwrp
  - tim/mtnpasi
  - tim/mtnpas
  - tim/cogwhl
  - tim/hexahead
  - tim/rcube
  - tim/flutter
  - tim/lensfla
  - tim/mulgim
  - tim/moja2F
  - tim/limpFr
pageURL: https://tim3.web.fc2.com/sidx.htm
downloadURLs:
  - https://team-apm.github.io/apm-data/package-sets-description.html
latestVersion: 2022/12/02
files:
  - filename: placeholder.pkgset
    isObsolete: true
