id: ePi/aulsMemref
name: Aulsメモリ参照プラグイン
overview: 他のメモリを参照するプラグインやDLLで必要
description: AviUtl version 1.00以降(1.10など)で使えるメモリ参照プラグインです。拡張編集は0.92です。
developer: ePi
originalDeveloper: yu_noimage_
dependencies:
  - exedit0.92
pageURL: >-
  https://scrapbox.io/ePi5131/Auls%E3%83%A1%E3%83%A2%E3%83%AA%E5%8F%82%E7%85%A7%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3
downloadURLs:
  - >-
    https://scrapbox.io/ePi5131/Auls%E3%83%A1%E3%83%A2%E3%83%AA%E5%8F%82%E7%85%A7%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3
latestVersion: 2021/05/23
files:
  - filename: plugins/auls_memref.auf
releases:
  - version: 2021/05/23
    integrity:
      file:
        - target: plugins/auls_memref.auf
          hash: >-
            sha384-O83zl2bsuzcynGveej15GrNPf3tRDdMz1P5jkpQB/PYX/R+Oh/7XFBFWf8Z/NXRi
