id: aoytsk/pluginlist
name: プラグインリスト
overview: プラグインとスクリプトの一覧をファイルに保存
description: プラグインリストはプラグインとスクリプトの一覧を、エクセルなどで閲覧できるtsvファイルに保存するプラグインです。
developer: aoytsk
pageURL: https://aoytsk.blog.jp/aviutl/1592487.html
downloadURLs:
  - https://aoytsk.blog.jp/aviutl/1592487.html
latestVersion: Ver 0.1
files:
  - filename: plugins/pluginlist.auf
