id: nazono/CameraAssistRuntime
name: カメラ補助プラグイン(要ランタイム・省メモリ)
overview: Aviutlカメラの移動方法を変更し、より使いやすくするプラグイン
description: >-
  Aviutlカメラの移動方法を変更し、より使いやすくするプラグイン。【動作にはVisual C++ 再頒布可能パッケージ 2015-2022
  x86(32bit)のインストールが必要です https://aka.ms/vs/17/release/vc_redist.x86.exe 】
developer: 謎の生物
pageURL: https://www.nicovideo.jp/watch/sm39701988
downloadURLs:
  - https://drive.google.com/drive/folders/1VcrWV_HF1fL2V_FfoV5wo5QBxzQuycMB
latestVersion: '1.7'
nicommons: sm39701988
files:
  - filename: カメラ制御
    archivePath: CameraAssist一式
    isDirectory: true
  - filename: plugins/xCameraAssist.auf
    archivePath: CameraAssist一式/plugins
  - filename: script/上方向ベクトル.cam
    archivePath: CameraAssist一式/script
releases:
  - version: '1.7'
    integrity:
      archive: sha384-r0LgY3xtc8EAhQw853HrfjCDtXzD/Eqb4sFihx7a7kUG4evlE+kqT2D1WKZkEWFz
      file:
        - target: plugins/xCameraAssist.auf
          hash: >-
            sha384-dw8X8XD9AnZdIYcZCYbZZ9Vs+wVsdoFkentZpN8EUd3q4l/EnsiUar1O4E961QKv
        - target: script/上方向ベクトル.cam
          hash: >-
            sha384-/RKqup7p1doYQTjB31kYDSUzo41vShlbU8CvYtjVNse1SonxpW5OdiAxpmtbUExq
