id: oov/prima
name: PRIMA File Reader
overview: PRIMAファイルをAviUtlで読み込めるようにする
description: >-
  これは PSDTool(https://oov.github.com/psdtool/) でシンプルビューを元にして出力できる PRIMA
  (Pre-Rendered IMage Archive) ファイルを AviUtl で読み込めるようにする AviUtl 用入力プラグインです。
developer: oov
pageURL: https://github.com/oov/aviutl_prima
downloadURLs:
  - https://github.com/oov/aviutl_prima/releases/latest
latestVersion: v0.1
files:
  - filename: prima.aui
releases:
  - version: v0.1
    integrity:
      archive: sha384-VMwnNzDguYIefiRDh0yASY5iQ0u8E4W8/InmepnsenBWLrj1ARuIYpcc9DBC8XPf
      file:
        - target: prima.aui
          hash: >-
            sha384-L2Dj2rkqxv2UMIvnhlSx33szBGK566GVGOSFCd7Bnob9HyNaLZkt2Pf1a815IkaB
