id: hebiiro/adjust
name: 最終フレーム自動調整
overview: 最終フレームを自動的に調整します
description: タイムラインを編集したとき、最終フレームを自動的に調整します。
developer: hebiiro
dependencies:
  - exedit0.92
pageURL: https://github.com/hebiiro/AviUtl-Plugin-AdjustLastFrame
downloadURLs:
  - https://github.com/hebiiro/AviUtl-Plugin-AdjustLastFrame/releases/latest
latestVersion: 2.3.1
files:
  - filename: plugins/AdjustLastFrame.auf
  - filename: plugins/auls_memref.ini
    isObsolete: true
releases:
  - version: 2.3.1
    integrity:
      archive: sha384-cH8TGh5+3bWx8gSRorVecWhcl2OQdVwREE0JwmA4chPzkPSQeL4CF0iWxRwdwNvn
      file:
        - target: plugins/AdjustLastFrame.auf
          hash: >-
            sha384-zCwbnbJB2zmUke8kKWsUWBJVb/V/TIebSVLA+MhQCP1fIEftduUMVfOpM9FVg4bV
  - version: 2.3.0
    integrity:
      archive: sha384-Y/Y814xvyRzOu3oSHGwq4mJaAiWroNmurXSj8bTOYQaWZgkbkGds/LkLM5N1ZBiG
      file:
        - target: plugins/AdjustLastFrame.auf
          hash: >-
            sha384-DqngJjpYSGpmyhb/18owItvvm0HUXNVU6A5tsVBsa9LUR+ei8VqzlIrF8EhD0qon
  - version: 2.2.1
    integrity:
      archive: sha384-VNZcthm805RBE5ESZfRe4UNy+asEuNRF6rEcs0XclApusIGMorKQnp0DtEVwVmHK
      file:
        - target: plugins/AdjustLastFrame.auf
          hash: >-
            sha384-/fn0xUi0i3IcvGHm3ghQKAVgCCrNZPb4yDfPyKivA1Irtyumetv4hv3gr9+dkTJ/
  - version: 2.2.0
    integrity:
      archive: sha384-rXHUp0TJQKCcGMUW0FHsvNQa+VIm3XFqwqiTF0ZLXH6UsL/ZcokzBX2OSbH32lLB
      file:
        - target: plugins/AdjustLastFrame.auf
          hash: >-
            sha384-YIKcJcJReKVGXkS9KcnnoPxBOfX36M8AWrTjbrPIWfBt7a95vSQ93ffhX1dEy4d/
  - version: 2.1.0
    integrity:
      archive: sha384-s/RfwSsO6lGED0bj9waZinWQJnuXKgaI+pLFYkCvFvUUr/msJOGUNfxh3nEK6h4j
      file:
        - target: plugins/AdjustLastFrame.auf
          hash: >-
            sha384-rRzmagpXBbooaPmoV4+on34eN3WCTpqrV9P2QdRYUSOaWi+sPlKnaY8cYYcQxOVA
  - version: 2.0.1
    integrity:
      archive: sha384-OtWYmYoEEKmZh6fl1Eur3R+Y6LV2GfT3jDUhz/dku1WKExdlW+9SnRYF/iF4a7QP
      file:
        - target: plugins/AdjustLastFrame.auf
          hash: >-
            sha384-W9HMlW5SoV3eA6xLnbTEspquzStGKquUpcFZQj0/g+D5knetzcEuNUeRbTk3kmZ9
  - version: 2.0.0
    integrity:
      archive: sha384-fmIiMyAdo8mkcQgxD7c3LUyrT6Us6AXtY1GZGAZK17RLtGEd3XqEd+DeCFFZkU3L
      file:
        - target: plugins/AdjustLastFrame.auf
          hash: >-
            sha384-0Tfrhp5NAr4y8tHwILbFMRckJABteoonYzTxlVhvyUI15+iAyIPM07nxQB13BUhQ
  - version: 1.0.3
    integrity:
      archive: sha384-VNVpEF3UJfsE7dpTPZQmzr1sDgN++IhbBel3oDkxl0JfFRBK2mtp5/8+nxb/iBav
      file:
        - target: plugins/AdjustLastFrame.auf
          hash: >-
            sha384-FQ6X6IakV1rYqKzQ6CdEPqcg8Nr8CQQ7f9okkeCrXIAKG3Y5kzXBbT4xjBEYZmAY
