id: MaverickTse/AviUtlSvg
name: AviUtl用SVG カスタムオブジェクト
overview: SVG画像を表示することのできるカスタムオブジェクト
description: >-
  カスタムオブジェクトとしてSVGを読み込むことができます。SVG画像は拡大しても、ボケません。【動作にはVisual C++ 再頒布可能パッケージ 2013
  x86(32bit)のインストールが必要です 
  https://www.microsoft.com/ja-jp/download/details.aspx?id=40784 】
developer: Maverick Tse
pageURL: https://www.nicovideo.jp/watch/sm23347189
downloadURLs:
  - >-
    https://onedrive.live.com/?authkey=%21ABNo3i9YR5%5FdnT8&id=26840CDF9818EB8E%21349&cid=26840CDF9818EB8E
latestVersion: '1.6'
nicommons: sm23347189
files:
  - filename: script/MaverickTse/@svgrender-JP.obj
    archivePath: AviUtlSvg/script
  - filename: script/MaverickTse/svgrenderーJP.obj
    archivePath: AviUtlSvg/script
  - filename: script/MaverickTse/svgrender.dll
    archivePath: AviUtlSvg/script
  - filename: libcairo-2.dll
    archivePath: AviUtlSvg
  - filename: libcroco-0.6-3.dll
    archivePath: AviUtlSvg
  - filename: libffi-6.dll
    archivePath: AviUtlSvg
  - filename: libfontconfig-1.dll
    archivePath: AviUtlSvg
  - filename: libfreetype-6.dll
    archivePath: AviUtlSvg
  - filename: libgdk_pixbuf-2.0-0.dll
    archivePath: AviUtlSvg
  - filename: libgio-2.0-0.dll
    archivePath: AviUtlSvg
  - filename: libglib-2.0-0.dll
    archivePath: AviUtlSvg
  - filename: libgmodule-2.0-0.dll
    archivePath: AviUtlSvg
  - filename: libgobject-2.0-0.dll
    archivePath: AviUtlSvg
  - filename: libiconv-2.dll
    archivePath: AviUtlSvg
  - filename: libintl-8.dll
    archivePath: AviUtlSvg
  - filename: liblzma-5.dll
    archivePath: AviUtlSvg
  - filename: libpango-1.0-0.dll
    archivePath: AviUtlSvg
  - filename: libpangocairo-1.0-0.dll
    archivePath: AviUtlSvg
  - filename: libpangoft2-1.0-0.dll
    archivePath: AviUtlSvg
  - filename: libpangowin32-1.0-0.dll
    archivePath: AviUtlSvg
  - filename: libpixman-1-0.dll
    archivePath: AviUtlSvg
  - filename: libpng15-15.dll
    archivePath: AviUtlSvg
  - filename: librsvg-2-2.dll
    archivePath: AviUtlSvg
  - filename: libxml2-2.dll
    archivePath: AviUtlSvg
  - filename: pthreadGC2.dll
    archivePath: AviUtlSvg
  - filename: zlib1.dll
    archivePath: AviUtlSvg
releases:
  - version: '1.6'
    integrity:
      archive: sha384-JR5E8ssS7UbhcGkU1MMmFrqQ4dKFcqCk9l0Pgh3G6ht9kNKIGU2T8upXe2Q99SKz
      file:
        - target: script/MaverickTse/@svgrender-JP.obj
          hash: >-
            sha384-xxpyPP5dLGrVwrMyWbL0G+xrhHD32muiyDmf26M4t0++dlxQe9QQuQz881TRQeOx
        - target: script/MaverickTse/svgrenderーJP.obj
          hash: >-
            sha384-Vew96ssVMtI9+epmygF/XtRlwtBFoj3jKti4QQh5vwNHerEmPNSgV5CY6vRlLapN
        - target: script/MaverickTse/svgrender.dll
          hash: >-
            sha384-1MtGv6v9QQXC8jhgnJaZUnoyB66SpwM1DwvVzG7oImptH1lDMbMfMTQGhyzA+Cn2
