id: rigaya/VCEEnc
name: VCEEnc
overview: AMDのVCEを使用してエンコードを行う
description: >-
  AMDのVCE(VideoCodecEngine)を使用してエンコードを行うAviutlの出力プラグインです。VCEによるハードウェア高速エンコードを目指します。
developer: rigaya
pageURL: https://github.com/rigaya/VCEEnc#readme
downloadURLs:
  - https://github.com/rigaya/VCEEnc/releases/latest
latestVersion: '8.23'
files:
  - filename: plugins/VCEEnc.auo
    archivePath: plugins
  - filename: plugins/VCEEnc.ini
    archivePath: plugins
  - filename: plugins/VCEEnc.conf
    archivePath: plugins
    isUninstallOnly: true
  - filename: plugins/auo_setup.auf
    archivePath: plugins
    isInstallOnly: true
  - filename: plugins/VCEEnc_stg
    archivePath: plugins
    isDirectory: true
  - filename: exe_files
    isDirectory: true
    isInstallOnly: true
  - filename: exe_files/VCEEncC
    isDirectory: true
    isUninstallOnly: true
releases:
  - version: '8.23'
    integrity:
      archive: sha384-N4toyEi+vl3o+qj2hh17z+PQUfTzUxR7cv+70Tdq9CBSH910AjwT2AcDke3SsOq7
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-soc5FyNwqElDvJ+z25+DR88TsXvbMcQm6mzEuH9CWAWIi8MsGgjAq9vMjxYIBSWo
  - version: '8.22'
    integrity:
      archive: sha384-ef8iWLpdBCopPe8HLs7um1m9EKIe0MS63oRSEGUpHiocbZpdsUXZRupNLfXIEhSy
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-p17Cw1GK3Vro4AQFQfGjNM9I9SwJaycHWcIPRQBa4AZEaVppE+7g+UM6V1sRHfjD
  - version: '8.21'
    integrity:
      archive: sha384-nIMxJdWz7qVCoMQbKfioKScRsxNpzmMDlIm1TN4dnyqBhIy4zCGXd0PzdmxVl7ed
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-boqAOh3wzSqzPxAFMMiPk45g0cOccBfiTc4kY1o4VDLsIxoS2Oz+i/XEqxasmt/e
  - version: '8.20'
    integrity:
      archive: sha384-S2AonS4GK91uE8J//+PurFGfa3ATRTmuKvHClyUlK7z2iji2HXkivnNoxaTPoSLg
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-SaIqO03qkM7D1cfwHdHlAcv7o99mRSXstV3yWErVSJ2DYbDhsAGrgrfxrdWGmKER
  - version: '8.16'
    integrity:
      archive: sha384-hYKzhFOm4OE7rqbFzOXk3B1vyt1YiB3HoxWAiOHeSxIv+5s7aZSUQopsdy7aHWjh
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-pyysgrhOAsc/x0C3BpZwvf9V9YVhS01q6WKA+2H9bXUmfvBM8mba7zFjSVrrV5pb
  - version: '8.15'
    integrity:
      archive: sha384-iMfLaxKyOih++HkopFH8miWZEpjP1kDxA2J/7x0vvduz79dWV6An5Pxt0j76lN4r
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-AYC3HlA8zkWgMFsJ2faXtSMGZOWjuXqmJ7t5XpGS3mSBQRFaIf42DhvK1wK+d/G7
  - version: '8.14'
    integrity:
      archive: sha384-xWiJiYJr5LmtgmkVD7A3t/blc9DCQwtLpeTycCG/mZ+eXgTfeoGdHYOxsRqAz0xH
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-r0zSXUtVHtMeNTWbW2XAlfbOCYhr8ux5lLy4SMxA2fQVbgxNjeLJNz6WMGEi3Q3B
  - version: '8.13'
    integrity:
      archive: sha384-HQ15/qNt8c48HzajGD2uxgRCW2FX5BAWWcAApq6YAEulU10WF2dmCM7st9DrZkn2
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-ang+M8+clbfQq3XmKNiqwRsR2shurtiCnWltw1L9mf3bzaddnMUT0hv+fBbY5/Ya
  - version: '8.12'
    integrity:
      archive: sha384-uKpv2mrtNTGtvH/9DEHDHRNqS2Tw3MJbleaiORZTh9Mro8tnsRsCbg6RJmYbHjxD
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-R0LdeewwlQ4oe08APwe3M1SM1YNjeOrW2UAxuskycUdJoObJUFsUjaRMLi56oAsj
  - version: '8.11'
    integrity:
      archive: sha384-Ezv1pqkHCVaF0uhLBs20OkL4bi8XupSkTcRpwcmESYcjMtXSfgnbZe8TaHDg2bln
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-aKuX7Ubl5n1xFV+z1Sop+s5gZnO0VmMYyqsoj5YOPWZr8PItcg+QYuR+VhAj+a4l
  - version: '8.10'
    integrity:
      archive: sha384-zzpMXGxq3HBj2ts2iaaPB8vXHREose7t/8toNBdQnRHHH5BEOq4E0YWH8gGs8wnB
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-tGpEzyMIQfyggyVI3Bx5ApFOFo0/cYmkVKdPAQ71O5ohjSXTcE88Av1IHai7eMxZ
  - version: '8.09'
    integrity:
      archive: sha384-eN9f6m/ffRJNRLpPkewCJxhjF9kgmtpwkr7DK/zpAyzAK3f9SFAl3e3dq/guaSeR
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-lOyx6wZHNvx56omkcAsrbbvtXxls5cevqj9aHAESV16JSXCelEbJ5kW0xiD2ULGZ
  - version: '8.08'
    integrity:
      archive: sha384-jc8PK6QR6Kz4T0JgmqttTJFdgnxM8vP4/X2U8126bbAu19ZcAzuUD7+99koA/klC
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-3B+3hPaTy/tfM3Fe0vzGfdW7NX9ZKE2J+BYkSqxicJBpUGu69deBF5sqp/mVR68s
  - version: '8.06'
    integrity:
      archive: sha384-um36qMAWfpY84Dq7Peg0QPWcfTUkNC0DwmrM/r7j0E+quNAEouFhFYr8gUB80Dds
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-eWrNeOEGFYrLtdteh2Sy1ZgS2HPDHqH6dJwolEDqQGb7r9FMSrW5tdXyvr2xHFRd
  - version: '8.05'
    integrity:
      archive: sha384-p2S4WIlPDXEd68kRtSyppIHU2BklbbIR7Zs5T5rcgN3Dr+kUbjpJ6Rd24ZFQ2i02
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-8cJZXs5fGdRx2fdOSoM44uLIJnQWjUvfGIxH+KEMmIJ7kPDmdV+G293z4EMjCH7W
  - version: '8.04'
    integrity:
      archive: sha384-c5IiTrKOOlQ+VliSFtR4k/po0U12Zm5cZULjJ9MyU1PLwgDmVSjpVyrg/ROLTBdi
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-whz+OS9bCGwb1nrUO0kFvhnQwlns/Z2nsIO5D44YXsW122XLE8DGcWC9dz9uSsLU
  - version: '8.03'
    integrity:
      archive: sha384-v7IHniHxQM+/Fau3W4GPcV1YvzCCdC/FMETeicl47xkvhAJplr/yBygciE/ri+Gs
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-JgFnxCJ/v1Q9zhznhJZM9Dd8x/EVADL3IB/zmbIKiVF+KzQVoSf+VN9zzGkoxLjr
  - version: '8.02'
    integrity:
      archive: sha384-rgxaxvsMj90AHr7q0bG6XUWm6Z8at3WWcGrAmJsnvK6mLtNKJpQyenUvxN8/5NSJ
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-s3PsLhclyGck1quciQHUbwf2hgSyRV0oNUTFToHYtI8WYp81uPZJZTvaujM41v1G
  - version: '8.01'
    integrity:
      archive: sha384-u7cv1vy2EkrIPsGLk+hUwJAKfWSiyqHog8VQx+TQdF8V4TxxQYc0YSzURYCl/QoJ
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-Vog4hCN5b5cqe4bwGK14irCmOPmanFk46QrvPnsQiDAqBDW04pvsnlXUcI//pOTW
  - version: '8.00'
    integrity:
      archive: sha384-qG6IXh+h+yWy48GToSXbgBpk7zSTtL91UXvk06jnzIZ3c7tSJwVXv7KtdR9M1QgQ
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-ZDnP+NVzxUmLcCCzs3hnBs0s5ouLmhBQST8Sn9L3jlSzE4vogKGIJK4/+FshOGxW
  - version: '7.18'
    integrity:
      archive: sha384-nVujnDtKOmeHF20Y4V07/bCOvTEECTQ4+qryRNlP+/ZprsBF+oBsAFjNwGZioU30
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-xVp6yvVdzKsjI+qzBtFUVYedjjhDBxqAQ0zitbxs+Y6sQd97vGEyeL6BUlDt+uuL
  - version: '7.15'
    integrity:
      archive: sha384-G3l5Pzy7n3VpfuujF33NZBnNjP9bdTSDN+WJQsBcZQmMh9H8tHfYrJ6OSN3GAIs+
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-58/4Q+s4vV0dEv8nI1DWyoYJ/T2Pm9IWQMWtew6R03tqZ2pSMXV7XLbmJuXZiEyA
  - version: '7.14'
    integrity:
      archive: sha384-hDfSEJjFwRQ8Ep8YydgoBUAwKLIUQGIc+8TFgjHtVQLg2dnTxchIIoiYhtNtIrep
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-oZsZA91/sJoNxP/x6sYQWKBTY2nb3Vz4vHP4uLDFS3C3SWYbko4HDQiWkMpdUssP
  - version: '7.13'
    integrity:
      archive: sha384-6Gt84Bc2nNNFygehRlEbIXTTJZalTm7DHWyphMsLK0ix/cvl/TcQ/jgB3qzaLqIa
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-T2m/Qk0qTvz1mJwF12V9MICRUG3eMlNqD6o8Ss8AoiWcPowBzW/24KU/alLac8wD
  - version: '7.12'
    integrity:
      archive: sha384-elHv+DDEuqSb7uV8il/qwkoq+b8o1zGc5S2w1RZ2Yp+cBaKi4PVPsyFf0NtYBKwL
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-wc14167rHE/rU5RJ6aewHG6SKoVvPufssX7AvUnRK3fa8NArXI5Au9JCAMTalbJ6
  - version: '7.11'
    integrity:
      archive: sha384-2TD+QBcD8qJ04Qo7OqfKaD2/1LxiPHLC35i78YsFvFs1G9HRHzPdym+rnel1ZKmu
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-p82Kt/n9arW9QJCunZAFvkOBd3s71WchoQeZphrlu1nVN3aMWhfsAojl7MvRpSs4
  - version: '7.10'
    integrity:
      archive: sha384-YYRMar5EzaE/YuqnPqEyqaK4a2fFutMxD+HfUqnvNX68YtMRT6Y6YBEy1J+sNXez
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-73R9cbGOM0ejkkyvCdqIIX77rWvAffzoXsr6g9ZxAcGxda8ecsTAloIsTqHNdnPH
  - version: '7.09'
    integrity:
      archive: sha384-vOtfug/f1QwINOBiPuR70jtKOITEpdxxSZZTozxgdTdW3AKYty5/fN7pj4i3JQ05
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-20nfFDEyTNR1Z2Vu0SBXEkBphae4zmoyKn/EP+1C8b2OcC4Xkzg0EauSZhclEkhJ
  - version: '7.08'
    integrity:
      archive: sha384-VunNZoFgz7dslfyfNT3Gqm1IL3gesGy3DVWwAuknbgPfuReu9pIH3lJCKJV1t1t6
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-pUcIkbZ0+vxUz7U7m2CBI3mi/n7E49zdY3EZlXRFbdXJWD1tnt/4rFD3SWo6zFrd
  - version: '7.07'
    integrity:
      archive: sha384-TT/9neqKHL4iwo6QZJeUfSE1vanrLX+1Qx/ljZPSwPwuAyB4rOIp8Ht/IKMplGas
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-uRown4XgUJjQPT99oFloflko8cbENqlbbuQArI3kfhM7SZnxttRA2dHDVCtSaXGI
  - version: '7.06'
    integrity:
      archive: sha384-hG45AyHmDBzLNk7e4g08SIxuN67EXUKmj5aYq4QKL9XxJb/NnRcywziK9qyYWHW7
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-AGSjGCa7WoFBNuoam7mvgxRRIEdgUFu5x2a6YJkkbnmmXP9+pAs8Zwb5ivuK8c6W
  - version: '7.05'
    integrity:
      archive: sha384-F/bfwYdPu9PPMit1h4fDf0Pn7u29wFTxsKEcXlI2q+sHefdfgD4Ud854EbMekHjt
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-mf1d+AvdQ6oEHhPAk0dGnaTYeHovdVGGxiDpstjmcdsqtavs4YH6Z4eTy40Mz2FG
  - version: '7.04'
    integrity:
      archive: sha384-R7EJUmnlSoRve76tg7x38aXmFSUB5+tXDFCEIUAtRULMVaPCemSmbCe102B2uXnj
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-fBRIC5BOxjTWW8onV2AZ3RnNf92nCIpb7n+/IB+IYEULbsKWo+AJ3axejIDV790r
  - version: '7.03'
    integrity:
      archive: sha384-/GWBhrGRoAmCE2cnIpgx3aXJTt1qzUH+09/6LaySC0Xhy7z+KQbXxNfev3tcOm1k
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-KmOxy7HiZioPlvjcobxNclVdMtUpychK9ZTmwsd3BN1pTVdeAHb6xvUMSbgWGW+q
  - version: '7.02'
    integrity:
      archive: sha384-Td2lWaV9JDbyt+dApDxGv9HWXBH/6n1oRZ70ckXVKyi8fH7kC2AuHbam4Qc1Xj2e
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-3/Zmr0tpDUIUOnYhpzKVrV45AmNrcUwBIgiY9PtCqkNZZAxl85dgalI6qZTZgtWR
  - version: '7.01'
    integrity:
      archive: sha384-YOB9fuRCLkHjx5AnZxquF22FfMgcyw69ypk1onXetU14tAmW5u6k9DgFsA9c0vih
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-7eK87bff3nXpSekqmRPYMmgDhIf0bF+MjdUAA3puOGi5lWB98D5k+wHmfg+aijWo
  - version: '7.00'
    integrity:
      archive: sha384-MoV6uktyg1dmf0ZldsetV/E+pruHLi9QxPVDbaJ84D6WaouzElR2sYpks4SoILkJ
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-OwkPhPf2hBcSjgR3vjuMOBZnKfK7tIEoWAfGITCLnQKYg+8H337L0XWClWNK1mb3
  - version: '6.17'
    integrity:
      archive: sha384-eET4ztZyPR5OTD4XxNfZMB1NMnqCAtWMBvx1xH/rkZVLHKqy0FjhZq8CcFYussxs
      file:
        - target: plugins/VCEEnc.auo
          hash: >-
            sha384-Nw+jRqn07dpSir9+3SAcBqiGfe2jFL22TiivDPbQZ8ZJOiSOzXDy85JFs1GHlWTW
