id: oov/aviutlBrowserMinecraftSkin
name: マイクラスキン
overview: マインクラフト風モデルを描画する
description: >-
  AviUtl + 拡張編集 + aviutl_browser
  の環境で使用可能なマインクラフト風モデルを描画するカスタムオブジェクトです。スキン画像を読み込みで適用することができます。
developer: oov
dependencies:
  - oov/aviutlBrowser
pageURL: https://github.com/oov/aviutl_browser_minecraft_skin
downloadURLs:
  - https://github.com/oov/aviutl_browser_minecraft_skin/releases/latest
latestVersion: v1.0
nicommons: sm38836771
files:
  - filename: script/browser/@マイクラスキン.anm
    archivePath: script/browser
  - filename: script/browser/@マイクラスキン.obj
    archivePath: script/browser
  - filename: script/browser/マイクラスキン-歩き.exa
    archivePath: script/browser
  - filename: script/browser/マイクラスキン-走り.exa
    archivePath: script/browser
  - filename: script/browser/マイクラスキン.exa
    archivePath: script/browser
  - filename: script/browser/contents/マイクラスキン.abc
    archivePath: script/browser/contents
releases:
  - version: v1.0
    integrity:
      archive: sha384-xo7xw1Ps6sfp7hd7cAaSWdu2IVFzErwoPf9GKzY0IHqg6IrXIdtq+jY09S5lBeqM
      file:
        - target: script/browser/@マイクラスキン.anm
          hash: >-
            sha384-C1rfgmQDr/3t6+P5tnJufs8MRbPz8ArKKW3LLrDgvEEfpm6ZCaLFjT4DXc/XpOmf
        - target: script/browser/@マイクラスキン.obj
          hash: >-
            sha384-zhkobUsdgjcPDkVMcmNU05oG1kuf7Ch4ksmuJudJEkl1A3jbrPTktrF9lwEyBcdv
