id: hebiiro/DragFilter
name: フィルタドラッグ移動
overview: フィルタをドラッグして移動できるようにする
description: オブジェクトダイアログのフィルタをドラッグして移動できるようにします。
developer: hebiiro
dependencies:
  - exedit0.92
pageURL: https://github.com/hebiiro/AviUtl-Plugin-DragFilter
downloadURLs:
  - https://github.com/hebiiro/AviUtl-Plugin-DragFilter/releases/latest
latestVersion: 9.3.0
files:
  - filename: plugins/DragFilter.auf
  - filename: plugins/DragFilter.ini
releases:
  - version: 9.3.0
    integrity:
      archive: sha384-nGYfLqwXG3IdzSyiJ5of6xIe0DpBIpfXjlHJxvsaLT0/4sa9rLkOWsYz/Hwkip2n
      file:
        - target: plugins/DragFilter.auf
          hash: >-
            sha384-Pqf1rjv9YIs4sBoGBhwfcLRZce8uXGeYcXKFLgb4VcXZoeD+tlunKSy7A0pG60Xg
  - version: 9.2.0
    integrity:
      archive: sha384-IPqzpFQugu/vJv9rVjsvltcz6URZvmf4fN7wIelEeRJebNQBkXyxzJe2v6aBi5ID
      file:
        - target: plugins/DragFilter.auf
          hash: >-
            sha384-hvHxldRgnZLrd3EiKbxNu+7E6y2PF5yoX3SV+Xn3voi/X6HSNbmAGhP5y+0catOA
  - version: 9.1.0
    integrity:
      archive: sha384-jpcn+g/x5H1oyFUZMYFTZ6bej8zep8Oxp62/f6Z23/dPvrDMi0V0m/5cvsyrA2cw
      file:
        - target: plugins/DragFilter.auf
          hash: >-
            sha384-roFvsQB8i8t05f0aoStSc2IQUYqnjepYO7zcQqBj/wgU/CoGbfe2S2ydOu8POT59
  - version: 9.0.0
    integrity:
      archive: sha384-FcdP6AlbiiD46uqe+BeCna7VYgDZxWrlTbDXxGv8LAjMC8tUF0QFMk7d8YSpKkvM
      file:
        - target: plugins/DragFilter.auf
          hash: >-
            sha384-BdJmkN7hWY85hhB+5Js+JdhE0AzHku9DNttShHIt9WEjYmLn1xvXLsFbSXVHBbuA
  - version: 8.0.0
    integrity:
      archive: sha384-OOqFH26gO+3GtcUm+yOAbK6s80lg02i8IFey/2CEVR+2Ld9Od5RSq5k+B4aexG+N
      file:
        - target: plugins/DragFilter.auf
          hash: >-
            sha384-hqQV1fyQnVHwpB4kFxNW5B47O7TJwTkJu08zMJ6l2CL9wxe40piHKodQamybG/V6
  - version: 1.0.0
    integrity:
      archive: sha384-cC+vsryk+9F4LP32nAB+3ljqQRd3r8PvR7ESThP7YV8ZPJ+/K67d0gH+Nq2F7jpl
      file:
        - target: plugins/DragFilter.auf
          hash: >-
            sha384-UyWbNedy6Yyr+PFYQKfvKFmtKlQdXZftY6p/ONTwwBITRA24jB/qZJl9/yAJZJAp
