id: SEED264/pixelsorter
name: PixelSorter_s
overview: 高速なPixelSorter
description: >-
  Aodaruma氏の「Pixel Sort_A」をDLL化したアニメーション効果です。【動作にはVisual C++ 再頒布可能パッケージ
  2015-2022 x86(32bit)のインストールが必要です
  https://aka.ms/vs/17/release/vc_redist.x86.exe 】
developer: 星野なたね
pageURL: https://github.com/SEED264/PixelSorter_s
downloadURLs:
  - https://github.com/SEED264/PixelSorter_s/releases/latest
latestVersion: '1.61'
files:
  - filename: script/SEED264/PixelSorter_s.anm
    archivePath: PixelSorter_s
  - filename: script/SEED264/PixelSorter_s.dll
    archivePath: PixelSorter_s
releases:
  - version: '1.61'
    integrity:
      archive: sha384-Cez31FFQ7AV1cu1NkS/XEvrSGBfrXmiczHDIqg2cibd4pzOQGl2bqfiXGb4SKLYV
      file:
        - target: script/SEED264/PixelSorter_s.anm
          hash: >-
            sha384-/AsJG+8gPwzgQgjYuvsyYf/WS4VtUgaIwmQ7UjKWPuQyIGNQYqKha6RxkRi1ZBRL
        - target: script/SEED264/PixelSorter_s.dll
          hash: >-
            sha384-C0lZ6qAPIvpWX0wKM1k+yJN0CaHVA8py0synSFWxSKbku5IwqFzRlyHIBKqYsZuK
  - version: 1.61 (Eng)
    integrity:
      archive: sha384-7ksGhrwIZk+1iwOoMvAoDZMED5649WLJo/ipSih22GvST3AbEjW67LwCqNKmuJur
      file:
        - target: script/SEED264/PixelSorter_s.anm
          hash: >-
            sha384-9QMlucDkR1PTvulhjKU8A246jMmyOKS7dFSnLNRvDpUCKiF1m7zMt6FAGpNmCBE5
        - target: script/SEED264/PixelSorter_s.dll
          hash: >-
            sha384-qHXfXl4dEjXXmPletwsplAEExYgOY6V35NK7jYpx4jScwrkdihesMj4YgbouAlD/
  - version: '1.60'
    integrity:
      archive: sha384-Cez31FFQ7AV1cu1NkS/XEvrSGBfrXmiczHDIqg2cibd4pzOQGl2bqfiXGb4SKLYV
      file:
        - target: script/SEED264/PixelSorter_s.anm
          hash: >-
            sha384-/AsJG+8gPwzgQgjYuvsyYf/WS4VtUgaIwmQ7UjKWPuQyIGNQYqKha6RxkRi1ZBRL
        - target: script/SEED264/PixelSorter_s.dll
          hash: >-
            sha384-MZ15lOJgR2BZYXzJIYzjZzdY19FUY9s0YuSgRSkXfII6AnUDjedMIUUwxoQPOFOT
