id: AviUtlLab/itvfr
name: 可変FR出力(逆テレシネ)
overview: 30/24fps混在のソースを可変フレームレートで出力
description: >-
  30/24fps混在のソースを自動判定して可変フレームレートで出力するプラグインセットです。24fpsで動きが大きなシーンは24fps、それ以外は30fpsで出力されます。逆テレシネプラグインと出力プラグインのセットで動作します。
developer: AviUtl実験室
pageURL: >-
  http://videoinfo.tenchi.ne.jp/?%B2%C4%CA%D1%A5%D5%A5%EC%A1%BC%A5%E0%A5%EC%A1%BC%A5%C8%BD%D0%CE%CF%20for%20AviUtl#taa0bd65
downloadURLs:
  - >-
    http://videoinfo.tenchi.ne.jp/?%B2%C4%CA%D1%A5%D5%A5%EC%A1%BC%A5%E0%A5%EC%A1%BC%A5%C8%BD%D0%CE%CF%20for%20AviUtl#taa0bd65
latestVersion: ver0.9
files:
  - filename: plugins/itvfr.auf
    archivePath: itvfr/
