id: rikky/scriptSort2
name: スクリプト並べ替え管理(rm 2)
overview: アニメーション効果一覧の並び替えやフィルタのドロップ追加
description: アニメーション効果一覧を並び替えたりフィルタをドロップできるプラグインです。
developer: rikky
dependencies:
  - rikky/rikkyModule2
pageURL: https://www.nicovideo.jp/watch/sm30290540
downloadURLs:
  - https://hazumurhythm.com/a/Di0/
latestVersion: v1.5a
nicommons: sm30290540
files:
  - filename: script_sort.auf
    archivePath: スクリプトを並び替え2/rikky_module ver2用
releases:
  - version: v1.5a
    integrity:
      file:
        - target: script_sort.auf
          hash: >-
            sha384-y7kwRwjCt9It4CVstK6cP1SOmKkWJ2k+olGl9S2gkhoOw6TTnxY7y7TKoyvg+aSS
