id: nazono/SortEffect
name: エフェクト並び替え
overview: 拡張編集のエフェクトメニューを並び替え
description: スクロール有りの縦長エフェクトメニューを整理するプラグインです。
developer: 謎の生物
pageURL: https://www.nicovideo.jp/watch/sm40952636
downloadURLs:
  - https://github.com/nazonoSAUNA/SortEffect/releases/latest
latestVersion: '2.0'
nicommons: sm40952636
files:
  - filename: plugins/SortEffect.auf
    archivePath: plugins/
  - filename: plugins/SortEffect_Setting.txt
    archivePath: plugins/
  - filename: exa/ランダム間隔で落ちながら登場.exa
    archivePath: exa/
  - filename: exa/ランダム配置.exa
    archivePath: exa/
  - filename: exa/ランダム方向から登場.exa
    archivePath: exa/
  - filename: exa/リール回転.exa
    archivePath: exa/
  - filename: exa/円形配置.exa
    archivePath: exa/
  - filename: exa/何処からともなく登場.exa
    archivePath: exa/
  - filename: exa/画面外から登場.exa
    archivePath: exa/
  - filename: exa/拡大縮小して登場.exa
    archivePath: exa/
  - filename: exa/簡易変形(カメラ制御).exa
    archivePath: exa/
  - filename: exa/簡易変形.exa
    archivePath: exa/
  - filename: exa/起き上がって登場.exa
    archivePath: exa/
  - filename: exa/球体(カメラ制御).exa
    archivePath: exa/
  - filename: exa/広がって登場.exa
    archivePath: exa/
  - filename: exa/座標の回転(個別オブジェクト).exa
    archivePath: exa/
  - filename: exa/座標の拡大縮小(個別オブジェクト).exa
    archivePath: exa/
  - filename: exa/砕け散る.exa
    archivePath: exa/
  - filename: exa/振り子.exa
    archivePath: exa/
  - filename: exa/震える.exa
    archivePath: exa/
  - filename: exa/弾む.exa
    archivePath: exa/
  - filename: exa/弾んで登場.exa
    archivePath: exa/
  - filename: exa/点滅.exa
    archivePath: exa/
  - filename: exa/点滅して登場.exa
    archivePath: exa/
  - filename: exa/反復移動.exa
    archivePath: exa/
  - filename: exa/万華鏡.exa
    archivePath: exa/
  - filename: exa/立方体(カメラ制御).exa
    archivePath: exa/
