id: aoytsk/extext
name: 字幕アシスト
overview: エディタやブラウザなどから、文章を直接タイムラインに追加
description: 字幕アシストはエディタやブラウザなどから、選択した文章を直接タイムラインに追加できるプラグインです。
developer: aoytsk
pageURL: https://aoytsk.blog.jp/aviutl/1412254.html
downloadURLs:
  - https://aoytsk.blog.jp/aviutl/1412254.html
latestVersion: Ver 0.1
files:
  - filename: plugins/extext.auf
