/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Core {
  version: number;
  aviutl: Program;
  exedit: Program;
}
/**
 * AviUtl or Exedit
 */
export interface Program {
  /**
   * The latest version of the program
   */
  latestVersion: string;
  files: {
    /**
     * The name of the file used in the program
     */
    filename: string;
    /**
     * Whether it is optional during installation (Default: false)
     */
    isUninstallOnly?: boolean;
    /**
     * Whether the file is a non-uninstallable file (Default: false)
     */
    isInstallOnly?: boolean;
    /**
     * Whether it is a directory (Default: false)
     */
    isDirectory?: boolean;
    /**
     * The relative path of the file in the archive (Default: null)
     */
    archivePath?: string;
  }[];
  /**
   * Releases of the program
   */
  releases: {
    /**
     * The version of the release
     */
    version: string;
    /**
     * The URL of the released archive
     */
    url: string;
    integrity: {
      archive: string;
      file: {
        target: string;
        hash: string;
      }[];
    };
  }[];
}
