/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Scripts {
  /**
   * List of script distribution sites
   */
  webpage: {
    /**
     * URL of the script distribution site
     */
    url: string;
    /**
     * Developer's name
     */
    developer: string;
    /**
     * Description of the site
     */
    description?: string;
  }[];
  /**
   * Information to be added to the downloaded script. In case of multiple matches, the later information in the array takes priority.
   */
  scripts: (
    | {
        /**
         * Compare these with browser history to determine which script have been downloaded
         */
        match: string[];
        /**
         * Name of the folder where script will be installed
         */
        folder: string;
        /**
         * The name of the script developer
         */
        developer: string;
        /**
         * Script dependencies
         */
        dependencies: string[];
      }
    | {
        /**
         * Compare these with browser history to determine which script have been downloaded
         */
        match: string[];
        /**
         * Install as a package with the specified id
         */
        redirect: string;
      }
  )[];
}
