id: ePi/patch
name: patch.aul
overview: 拡張編集Plugin ver.0.92のバグを修正する
description: >-
  AviUtl ver.1.10や拡張編集Plugin ver.0.92に存在するバグを修正します。拡張編集Plugin
  ver.0.93rc1で修正されたバグも修正します。
developer: ePi
dependencies:
  - aviutl1.10
  - exedit0.92
pageURL: https://scrapbox.io/ePi5131/patch.aul
downloadURLs:
  - https://github.com/ePi5131/patch.aul/releases/latest
latestVersion: r42
nicommons: sm39491708
files:
  - filename: patch.aul
  - filename: patch.aul.json
    isUninstallOnly: true
  - filename: plugins/patch.aul
    isObsolete: true
  - filename: plugins/patch.aul.json
    isUninstallOnly: true
releases:
  - version: r42
    integrity:
      archive: sha384-NzhqC3mHg7CU9nKahrrS2gNCM1pHIo1pYDX0lTRmxr+am56PfwJk6z0kHbSFxCVL
      file:
        - target: patch.aul
          hash: >-
            sha384-mgsj+YkVkZksJCMglAKmljaLqb/1Dw6x6BP2fVvBCdElIjxgqNh/VA5zCNFd01Y9
  - version: r41
    integrity:
      archive: sha384-FLUNw993qwuxr14M6D8i6hJGkyUBinK9MV7yI1JNb1SOvofq+DpyTNxa2tRQggMM
      file:
        - target: patch.aul
          hash: >-
            sha384-qKiatKWsSq/EMGVe0jTCH4RQrW1JKFMtk6ih6Al762PXj1YB8e6FOagZmNrCBgci
  - version: r40
    integrity:
      archive: sha384-A13LDgDe7U3VISw4aynyS0n6J0IwvBTJYRXQrEIR1w2L8NB5NIJOjnz9e+hRmJik
      file:
        - target: patch.aul
          hash: >-
            sha384-ZtX8Lo/9jHPPb4pWBNC7l2E9206hmzeU6vE0mXDXR2JcuHwKlWXmTVv3hPVVWUOF
  - version: r39
    integrity:
      archive: sha384-19fA00HDL+AQN0JYW4zn9jACel7wvlkM2dS9Lm1lfbItOyrJqxrEJjU4zEPCiNS6
      file:
        - target: patch.aul
          hash: >-
            sha384-eH7y28hVln8BpM9BOd74cxi2DMWMtvoRk9GAMwGSbEdGYXT0cKsZ1766NudSkIDf
  - version: r38
    integrity:
      archive: sha384-DlSScpdsjseqyzh9kK3JPv0ia3xgXo3Q9UdvwoFaxoqcZ9+b4XCXcPS/9U+xHl8n
      file:
        - target: patch.aul
          hash: >-
            sha384-vfGWEVoW/wc+49pxu8YIw8XRRgOgiYvZMWB9SgQ2IaSgtJX8aYV6u30wAFGlON62
  - version: r37
    integrity:
      archive: sha384-YAKPJfW5vX5UkOgSJWnBE71v4aQd0kpdmRyQ8pe1WFZwU6mNqga/IQOMgGydHXQG
      file:
        - target: patch.aul
          hash: >-
            sha384-MrSZ1zSpTQqG6sISOKGym6GQDefQ02bmFFE0niI0SFsOs8znQzUliA5jl2rIHCle
  - version: r36
    integrity:
      archive: sha384-E6ojEYFcV0VSHMs+MFOUpXU7r39DOLmD0kdXZYEnmbLw1P6bB2Toe3FHmX2i1bxI
      file:
        - target: patch.aul
          hash: >-
            sha384-Wyf7pdnb2wfATVreZ8H/Q+6HV+GE5zrIBYcn+LXn4KT4cN6tmKblqVu+j+XfmLWj
  - version: r35
    integrity:
      archive: sha384-6a9Io+Vgp5a0HHOazPWzIGtt9UCHLQwiqC9ZV5qKtqi2VhaMxbTCshAVlpDuGBhH
      file:
        - target: patch.aul
          hash: >-
            sha384-IH4DIr29gbJDDBC/XeGhc9qjJzq6y+xchfxT1brBQndF//QWh4TifhiNQGlBWIcL
  - version: r34
    integrity:
      archive: sha384-MOG/Y53HMEOjSGr4mUEyIIgmhrMSvnNvZ3of5c4veFLNSOxSy57RW9RotEt+UqYn
      file:
        - target: patch.aul
          hash: >-
            sha384-mxrkq3sI3GVv+qp0m4VNl35EQz6T57jY1VPxy6HWAAVkhfv9SHFV9CByYRPrvCuU
  - version: r33
    integrity:
      archive: sha384-zGiUsrF6ryPeibl0+XSHHGcM09dsI2lVZOjTM19ojmZMYAiKCmzYqUo/EsL6mGxJ
      file:
        - target: patch.aul
          hash: >-
            sha384-tFooaV3b1EnZt+rTcZ5nxtFRQDs+y5UbDvxfjFbnXXTi3WMdMVGTeWBU65c2B7HX
  - version: r32
    integrity:
      archive: sha384-pMSjH2TIgNdbQuL3fvB67fFHIWCCljyHhLLNEaRhRweFthMRM3xfEY+oVCKFbIqN
      file:
        - target: patch.aul
          hash: >-
            sha384-tFo5eCiuP2r45MEnSveDX+1bbial9I7XRRbxBYdE0Hur2vqSRq7VQVcojtjSKCEK
  - version: r31
    integrity:
      archive: sha384-dFeD7afP1c7bQyM5XucT+1gUFzl/StCJHmm7NK8zfFafSw3LKmTyAw65HicT6OKK
      file:
        - target: patch.aul
          hash: >-
            sha384-7b7PA6iU+HhfsfOlI4n20gWg6A2gV7Zx/OXikmdrOMzZcmRFvYGYtpdv0oTOpl34
  - version: r30
    integrity:
      archive: sha384-Z4cU4wkZsnZs++f6sfNN1pWS4YmQVTvS6N/awd7KXULvbDxVkuES2WCGHnoXwaH7
      file:
        - target: patch.aul
          hash: >-
            sha384-JUpk8MybgdlQWuJPDFjv5X2c0CksgPDisM2jF1UU5ljQt8h9YpJ6OHNRcAVAu2UQ
  - version: r29
    integrity:
      archive: sha384-6irsNZtXbuGA38wmb0OY9tioo3v5lwxmZvrwV9UEC0334Tq9e88nDT0r1XSClx1Y
      file:
        - target: patch.aul
          hash: >-
            sha384-bxX8gVC5fQ2mww84zTs1Na9ehDBOQ5E1noikjUcspkRsSSjwjdaZiyc8lppMRToL
  - version: r28
    integrity:
      archive: sha384-5hqwY1MKKC7CHvMPncIg/2wwJKonG+DhE6nql1Ri+D/OfrivhEHkzrzVmBWz0thm
      file:
        - target: patch.aul
          hash: >-
            sha384-4J/MXO2dikDAuqhKsKxI3PO9juKvX2VEcgsl2nyJVMMPijzCgLNyFmiCAaJcNoEL
  - version: r27
    integrity:
      archive: sha384-Se7PWIbPe8Lqt2y2zkNH7M3gNH6bTfw9sy8B1bZB/HDgFbV7rpVZlQeitCFgjwIG
      file:
        - target: patch.aul
          hash: >-
            sha384-4Ec7q/hnwVSlog4ErQjbq7Y6v8zw9kEmgFk3Nb6bZOl+sx6A0Ba+IWBAU+KCY8oE
  - version: r26
    integrity:
      archive: sha384-onUPGoK1zrVHEweUzLws4ZifbxDd7Zhn6YFWJ6Y+zVWoopaiNOSwiG/VQkaw98im
      file:
        - target: patch.aul
          hash: >-
            sha384-0h2QiffmEsq2MyQkaDMgvdx+EYKbdHhLJejfNom21BzUE3Kkg2fsdM1vZ7mrQc69
  - version: r25
    integrity:
      archive: sha384-1OLPSFXJSYyWziYkklr9WiBh/nxE5baNajSx0yHPZlWqwnMw2QaqkWwwYQEtot8w
      file:
        - target: patch.aul
          hash: >-
            sha384-NgvKIy0ffAP864acW7CX9Uaj+ma/fmHVrELRppHVFGABmXZdHDqkPOZ6a6hcrwGD
  - version: r24
    integrity:
      archive: sha384-qu79DDFkB/7wJ7rhhDBSd1UEUplEd5WXhiIEuZUBkwBQn86rVmMTaUkbjyA9SmgS
      file:
        - target: patch.aul
          hash: >-
            sha384-S7u5l7ZY41+3Ix5DfvRCEZbXSuMeAEDXgnaf2BI4vc+p4JQUb5hsFno0m5uq4OJ9
  - version: r23
    integrity:
      archive: sha384-xS7nBPZKTymGoFV1Xi8BbqC7QCsd15O0VmnaYj3KXCQxR91L0cTbh/iFayKmdpsR
      file:
        - target: patch.aul
          hash: >-
            sha384-jwkoghMA3N4riudvr47ajHdHm5G6pvJvFnczXWCNRBh9F/9eoO2HBOl+2Pndij5O
  - version: r22
    integrity:
      archive: sha384-ZrWTR1MZhsO7Z+sLGy07MBmAM3blqjQRG7vESsK0fNDCoorOkfOP1I75c44sWM1U
      file:
        - target: patch.aul
          hash: >-
            sha384-dshqd6YS6QDzrkovMhB8gJNsIuVs8bQTIpzo4NguOluvcKSp/pEx0f++hLgRPncE
  - version: r21
    integrity:
      archive: sha384-e+ncEOFFohmPQW7lXbB6FEhN2ndPosHWEnuYgB4EIK6ilxKMuempHxvCY8wLzMS9
      file:
        - target: patch.aul
          hash: >-
            sha384-qFlcNnZJgBycyhjELZRNtejlElhK5AwxGLZnqspMCjUXpxc+duVgBtws3HI/36iq
  - version: r20
    integrity:
      archive: sha384-QVT2Tk2MJWbbYgxrYYP/NMFhshlh+rIlDyQuD7iOJed7HAWSytrch0vwWp0+wODG
      file:
        - target: patch.aul
          hash: >-
            sha384-uwy1GdmOQJk90QSLz/9TcMzPCXk4KWlN+Pnbu27QBeel1xeBVwKBOSea/UHC5K1X
  - version: r19
    integrity:
      archive: sha384-5+jMRlIpcax35H+fO4LOiCGT9Aul9ojWmAwe/Dlx/1rCNxRHD+/EQl+2Va4MmG6/
      file:
        - target: patch.aul
          hash: >-
            sha384-CbHLDY6VKlgWNQPE04LkX0DeyMJBiD/Q+Ma744JSanagv8439iURG/Ldvu050ul5
  - version: r18
    integrity:
      archive: sha384-DWlZ/6e/EzYWR5CLOoPcxhOdDgayd8vvV6+cQ2bH4VkYzChvsRFSBSgMKouYS84J
      file:
        - target: patch.aul
          hash: >-
            sha384-gLFA2WC4y5iS2nPbuu1xCgvhApxVWMkB7ieex2vprK1BbOF4shzQ+f/toyFKW/+N
  - version: r17
    integrity:
      archive: sha384-EwxxnvUys0oT27JCtLglBfQcb2PaVuHKc5dYG5xMp17NGLqZEyQ2Px/xddWStBfO
      file:
        - target: patch.aul
          hash: >-
            sha384-0Pu2RDTMRB0D6j+Y4V8V1Ui1fz90XFGJThxvEfOGC3F/52NMV1WevRP8bq5Ky6H+
  - version: r14
    integrity:
      archive: sha384-F12wUu5o4f0Q4x7j86plKB7v1xNxB8EOKPXdJnHLnr+liunQN2CN8ViLvSUR6ohZ
      file:
        - target: patch.aul
          hash: >-
            sha384-tPCOyr4p2z/P+/eiuCz2ItcGoMGhBQRM43+jCheRLNzse9P4VCYz7TJiCGl1IaZX
  - version: r11
    integrity:
      archive: sha384-7cWPCn0miWYLWiAcIEVyDkZFidAPTZQQzMPRHsgaoUWIL7v2x3N+L96L+tjm4BAO
      file:
        - target: patch.aul
          hash: >-
            sha384-6W9VOV37w21UVMqBX2ItjSbTWarxkXg/DoQUjJpQaLpJRtIt8+itur5Vm3Q6wwOu
  - version: r8
    integrity:
      file:
        - target: patch.aul
          hash: >-
            sha384-Y5+kwXflyU0gp355bol79vADMCZVIZz0yV8mcPXB0lLxNRLxEzqfOJM8BpU1Td9Y
