id: nagomiku/paracustomobj
name: 値で図形
overview: 図形のサイズを縦と横で指定
description: 四角形などの図形をxyサイズを指定して作成することができます。
developer: Nagomiku
pageURL: >-
  https://scrapbox.io/nanikani-shugo/Nagomiku%E8%87%AA%E4%BD%9C%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%97%E3%83%88
downloadURLs:
  - >-
    https://drive.google.com/drive/folders/1l9-CCQ3-3umykPS8pqek3PgkZ4RUCkN2?usp=sharing
latestVersion: v2.10
files:
  - filename: script/Nagomiku/値で図形.obj
releases:
  - version: v2.10
    integrity:
      archive: sha384-IH+AsiIabSupJuZTL2hUSzNy9bJfL13ExL6fPX9QwgZE8V22yaYEANHB4CxAVBnQ
      file:
        - target: script/Nagomiku/値で図形.obj
          hash: >-
            sha384-IH+AsiIabSupJuZTL2hUSzNy9bJfL13ExL6fPX9QwgZE8V22yaYEANHB4CxAVBnQ
