id: nazono/redoRuntime
name: Redoプラグイン(要ランタイム・省メモリ)
overview: Ctrl+Yキーでのやり直し機能を追加する
description: >-
  AviUtlにCtrl+Yキーでのやり直し機能を追加するプラグイン。元に戻す関係のバグの修正も同時に行ってくれます。【動作にはVisual C++
  再頒布可能パッケージ 2015-2022 x86(32bit)のインストールが必要です
  https://aka.ms/vs/17/release/vc_redist.x86.exe 】
developer: 謎の生物
dependencies:
  - exedit0.92
pageURL: https://drive.google.com/drive/folders/1OBl9qLIWDYlAghXaNUj7Sfme7hpCSSzY
downloadURLs:
  - https://drive.google.com/drive/folders/1tg-kZSw6m3d5MLeKuA95UB8Kv_H2uoT5
latestVersion: v2.7rt
nicommons: sm39263447
files:
  - filename: plugins/Redo.auf
releases:
  - version: v2.7rt
    integrity:
      archive: sha384-hSHKjKjQwy1XTpuGuORffr7MDjzYTQqBy2gcHsdMFlcOqYrorflZRg/vIZ6rUgH9
      file:
        - target: plugins/Redo.auf
          hash: >-
            sha384-0s8DAzZIdJvw0aSKbMIALM3O1ddY414jbKj02ZrlMoncLppMN8Rd52FIuZKI71bE
